// <auto-generated />
namespace Ballpark.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class VenueDBSetMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VenueDBSetMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202005181603251_VenueDBSetMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
