// <auto-generated />
namespace Ballpark.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NewFirstMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFirstMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191440581_NewFirstMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
